### PR TITLE
Feature #18 option for generating svg or png

### PR DESCRIPTION
**Pull request by AmirSavand**

### CODE REVIEW

**Comment by Alir3z4** [comment]
@amirm3hdi Add the svg changer as well so I merge

Or you wanna do it in another branch ?

**Comment by AmirSavand** [comment]
@Alir3z4 I'll add switcher now, do not merge.

**Comment by Alir3z4** [comment]
Awesome, lemme know when it's done so I'll merge

**Comment by Alir3z4** [comment]
Fixes #18

**Pull request merged**
