### PR TITLE
Fix #25 py versions is not a valid action

### LINKED ISSUE #25: py_versions is not a valid action.
URL:

```
/pypi/py_versions/html2text/badge.png
```

### PR DESCRIPTION
**Pull request by Alir3z4**
Fixes #25

### CODE REVIEW

**Comment by AmirSavand** [comment]
Perfect but not perfect...

There are some issues here:
- The SVG has extra space at the right side.
- There's no shortened for it, 'pv'  errors.

**Comment by Alir3z4** [comment]
It's live again:
- PNG: [PNG](http://badge.kloud51.com/pypi/py_versions/html2text/badge.png)
- SVG: [SVG](http://badge.kloud51.com/pypi/py_versions/html2text/badge.svg)

**Comment by Alir3z4** [comment]
> There's no shortened for it, 'pv' errors.

I let that shortcut for later when we have more integrations , so I can think about a better abstracted way of shortening actions like that.

> The SVG has extra space at the right side.

both svg and png has 6 px on right and left side, @amirm3hdi can you make a issue about it so we can discuss it better ?

Thanks

**Comment by AmirSavand** [comment]
@Alir3z4 Sounds good.

**Pull request merged**
